= What’s in this break-fix?

== In this break-fix:

**Type of issue:**

FIXME: Describe an issue type/category that this specific issue falls into, like, "A Red Hat Enterprise Linux 7 system won't boot after a kernel update." Save issue-specific details for the break-fix scenario page.



**What you should already know:**

FIXME: This training assumes that you are a Red Hat Certified System Administrator (RHCSA) or have equivalent experience administrating Red Hat Enterprise Linux 7 or 8. FIXME - update this as needed


**How break-fix training works:**

. Challenge yourself in the break-fix activity. It describes a problem scenario that's simulated in the lab environment where you can investigate and solve the problem.
. Follow up with the guided solution:
.. If you weren't able to solve the problem on your own, read and follow the instructions in the Guided Solution to complete this training.
.. If you were successful in solving the problem, read the solution for useful tips you can apply when solving similar problems.