= Check your work

== Follow below steps in the lab to check your work

FIXME: Add the instructions to be followed in the lab environment to make sure the problem has been resolved. You may chose to remove this block if grading script is provided in the lab to check the work.

== Check your work using the grading script

After you have resolved the issue and met the success criteria, login to `FIXME` system as `FIXME` user and run the grading script as shown here to check your work:

[source,bash,role=execute]
----
break-fix-script grade
----

.Sample output
----
[root@classroom ~]# break-fix-script grade
Initiating break-fix-script with option grade
Grading.  Please wait.
Success.
COMPLETION CODE: <check your output for this value>
Completed break-fix-script with option grade successfully
----

FIXME: Remove the below block if no grading script is provided to check the work in the break-fix activity. In this case make sure you use the above block to provide step-by-step instructions learner can follow to check their work.

== Submit the completion code

NOTE: Skip this if not applicable for you.

- For RedHat internal audience: Submit that completion code https://link-to-appropriate-lms.com[here,window=_blank] to receive a grade for this training
- For RedHat partners: Submit that completion code https://link-to-appropriate-lms.com[here,window=_blank] to receive a grade for this training

FIXME: Change the links in the above lines to the link for appropriate audience specific LMS where learner can provide completion code. Remove this block if submitting completion is not applicable.