site:
  title: RHCSA Challenge Exercises
  start_page: rha-rhcsa-challenge-excercises::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
